ðŸ˜ˆ *RAWANA MD UPDATE AVAILABLE* â—

â— `Use .update` â—

ðŸ†• ð—”ð——ð——ð—˜ð—— ð—–ð—¢ð— ð— ð—”ð—¡ð——ð—¦:
â–ªï¸Movie detail card add - `.movieinfo`
â–ªï¸xxx video download add - `.xxx` 

ðŸ†• *NEW SETTINGS*
â–ªï¸Auto React Status - `on/off`
â–ªï¸Auto React - `on/off`
â–ªï¸Auto Read Message - `on/off`
â–ªï¸Always Online - `on/off`
â–ªï¸Bad Words Detect - `on/off`
â–ªï¸Link Detect - `on/off`
â–ªï¸Other Bots Detect - `on/off`

âœ… ð—™ð—œð—«ð—˜ð—— ð—œð—¦ð—¨ð—˜ð—¦:
â–ªï¸Movie command Fix `sinhalasub` ,`sub`
â–ªï¸Forward commad Fix `forward`,`f`
â–ªï¸TikTok download Fix - `.tiktok`, `.tt`

ðŸ“Œ ð—¢ð—™ð—™ð—œð—–ð—œð—”ð—Ÿ ð—Ÿð—œð—¡ð—žð—¦:
ðŸŒ Website: RAWANA MD Official
https://rawana-md-official-web.vercel.app/

> RAWANA MD
